backend:
  name: github
  repo: lulucuyvers/madocwebsite
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projecten"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Titel"
        name: "title"
        widget: "string"
      - label: "Beschrijving"
        name: "description"
        widget: "text"
      - label: "Hoofdbeeld"
        name: "mainImage"
        widget: "image"
      - label: "Galerij"
        name: "gallery"
        widget: "list"
        field:
          label: "Beeld"
          name: "image"
          widget: "image"
      - label: "Publicatiedatum"
        name: "date"
        widget: "datetime"
